spring.application.name=backend

# Kết nối Database (Pass của bạn là admin123)
spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db?sslmode=verify-full
spring.datasource.username=postgres
spring.datasource.password=admin123

# Tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081    